<?php

return [
    'settings' => [
        'hero' => [
            'badge' => 'Service · Fraternite · Honneur',
            'title' => 'Groupe Scout',
            'highlight' => 'Saint Nicolas',
            'description' => "Un mouvement de jeunesse porte par le service, la fraternite, la foi et le depassement de soi au Burundi.",
            'primary_cta' => 'Rejoindre le groupe',
            'secondary_cta' => 'Decouvrir nos unites',
        ],
        'mission' => [
            'subtitle' => "L'essence de notre engagement aupres de la jeunesse.",
            'text' => "Le Groupe Scout Saint Nicolas contribue a l'education integrale des jeunes a travers la Promesse et la Loi scoutes. Nous aidons chaque membre a grandir humainement, spirituellement et socialement dans un cadre de service, d'aventure et de responsabilite.",
        ],
        'values' => [
            'subtitle' => 'Les valeurs fondamentales qui accompagnent chaque scout dans son parcours.',
            'items' => [
                [
                    'title' => 'Fraternite',
                    'description' => "Vivre ensemble dans le respect, l'amitie et la solidarite.",
                    'icon' => 'fa-solid fa-heart',
                    'color' => '#c62828',
                    'background' => 'linear-gradient(135deg,#fce4ec,#f8bbd0)',
                ],
                [
                    'title' => 'Service',
                    'description' => 'Agir concretement pour les autres et pour la communaute.',
                    'icon' => 'fa-solid fa-star',
                    'color' => '#f57f17',
                    'background' => 'linear-gradient(135deg,#fff8e1,#ffecb3)',
                ],
                [
                    'title' => 'Aventure',
                    'description' => "Explorer, apprendre et se depasser a travers la nature et la vie d'equipe.",
                    'icon' => 'fa-solid fa-compass',
                    'color' => '#2e7d32',
                    'background' => 'linear-gradient(135deg,#e8f5e9,#c8e6c9)',
                ],
                [
                    'title' => 'Responsabilite',
                    'description' => 'Former des jeunes autonomes, fiables et engages.',
                    'icon' => 'fa-solid fa-people-group',
                    'color' => '#1565c0',
                    'background' => 'linear-gradient(135deg,#e3f2fd,#bbdefb)',
                ],
            ],
        ],
        'objectives' => [
            'subtitle' => 'Ce que nous voulons construire au quotidien avec les jeunes et les familles.',
            'items' => [
                [
                    'title' => 'Former des jeunes responsables et engages',
                    'icon' => 'fa-solid fa-graduation-cap',
                    'color' => '#1565c0',
                    'background' => 'linear-gradient(135deg,#e3f2fd,#bbdefb)',
                ],
                [
                    'title' => 'Developper le sens du service et de la solidarite',
                    'icon' => 'fa-solid fa-hands-helping',
                    'color' => '#2e7d32',
                    'background' => 'linear-gradient(135deg,#e8f5e9,#c8e6c9)',
                ],
                [
                    'title' => "Favoriser l'epanouissement personnel par l'aventure",
                    'icon' => 'fa-solid fa-route',
                    'color' => '#f57f17',
                    'background' => 'linear-gradient(135deg,#fff8e1,#ffecb3)',
                ],
                [
                    'title' => 'Transmettre les valeurs scoutes et chretiennes',
                    'icon' => 'fa-solid fa-pray',
                    'color' => '#c62828',
                    'background' => 'linear-gradient(135deg,#fce4ec,#f8bbd0)',
                ],
                [
                    'title' => 'Creer des liens durables entre les membres',
                    'icon' => 'fa-solid fa-people-carry',
                    'color' => '#6a1b9a',
                    'background' => 'linear-gradient(135deg,#f3e5f5,#ce93d8)',
                ],
                [
                    'title' => 'Preparer des citoyens actifs et utiles',
                    'icon' => 'fa-solid fa-landmark',
                    'color' => '#00695c',
                    'background' => 'linear-gradient(135deg,#e0f2f1,#b2dfdb)',
                ],
            ],
        ],
        'contact' => [
            'email' => 'contact@gsn.bi',
            'phone' => '+257 79 00 00 00',
            'address' => 'Bujumbura, Burundi',
        ],
    ],
    'units' => [
        [
            'slug' => 'meute',
            'name' => 'Meute',
            'age_range' => '6 - 11 ans',
            'short_description' => "Les louvetaux decouvrent le scoutisme a travers le jeu, l'imaginaire et les premieres responsabilites.",
            'long_description' => "La Meute aide les enfants a grandir dans la joie, la discipline et la vie de groupe, grace a des jeux, des chants et des activites adaptees a leur age.",
            'icon' => 'fa-solid fa-paw',
            'color' => '#F5C400',
            'accent_color' => '#FFF3B0',
            'leader_name' => 'Akela',
            'schedule' => 'Samedi matin',
            'gender_scope' => 'Mixte',
            'sort_order' => 1,
        ],
        [
            'slug' => 'troupe-f',
            'name' => 'Troupe F',
            'age_range' => '12 - 15 ans',
            'short_description' => "La Troupe feminine developpe l'autonomie, la technique scoute et le leadership en equipe.",
            'long_description' => "La Troupe feminine vit le scoutisme par patrouilles, les camps, la progression personnelle et le service, dans un cadre stimulant et fraternel.",
            'icon' => 'fa-solid fa-person-dress',
            'color' => '#C2185B',
            'accent_color' => '#FCE4EC',
            'leader_name' => 'Cheftaine Troupe F',
            'schedule' => 'Samedi apres-midi',
            'gender_scope' => 'Feminine',
            'sort_order' => 2,
        ],
        [
            'slug' => 'troupe-m',
            'name' => 'Troupe M',
            'age_range' => '12 - 15 ans',
            'short_description' => "La Troupe masculine forme des scouts capables de relever des defis, de servir et de mener une patrouille.",
            'long_description' => "La Troupe masculine apprend aux adolescents la vie de camp, l'endurance, l'organisation et le sens des responsabilites a travers la methode scoute.",
            'icon' => 'fa-solid fa-person',
            'color' => '#2E7D32',
            'accent_color' => '#E8F5E9',
            'leader_name' => 'Chef Troupe M',
            'schedule' => 'Samedi apres-midi',
            'gender_scope' => 'Masculine',
            'sort_order' => 3,
        ],
        [
            'slug' => 'grappe',
            'name' => 'Grappe',
            'age_range' => '16 - 18 ans',
            'short_description' => 'Les pionniers vivent des projets concrets, des actions de service et des experiences de maturite.',
            'long_description' => "La Grappe encourage l'initiative, la responsabilite collective et la contribution a la communaute dans une etape charniere de la jeunesse.",
            'icon' => 'fa-solid fa-people-group',
            'color' => '#1B4F9B',
            'accent_color' => '#E3F2FD',
            'leader_name' => 'President Grappe',
            'schedule' => 'Dimanche apres-midi',
            'gender_scope' => 'Mixte',
            'sort_order' => 4,
        ],
        [
            'slug' => 'route',
            'name' => 'Route',
            'age_range' => '19 - 23 ans',
            'short_description' => "Les routiers approfondissent leur engagement, leur vocation de service et leur vie d'adulte responsable.",
            'long_description' => "La Route accompagne les jeunes adultes dans leur cheminement humain, spirituel et communautaire a travers des projets ambitieux.",
            'icon' => 'fa-solid fa-person-hiking',
            'color' => '#C0392B',
            'accent_color' => '#FDEAEA',
            'leader_name' => 'Chef Route',
            'schedule' => 'Dimanche matin',
            'gender_scope' => 'Mixte',
            'sort_order' => 5,
        ],
        [
            'slug' => 'amical',
            'name' => 'Amical',
            'age_range' => '23 ans et +',
            'short_description' => "Les anciens et adultes soutiennent la formation, l'encadrement et la vie du groupe.",
            'long_description' => "L'Amical rassemble les adultes qui accompagnent les jeunes, appuient les projets et transmettent l'experience aux nouvelles generations.",
            'icon' => 'fa-solid fa-people-roof',
            'color' => '#5D6D7E',
            'accent_color' => '#ECEFF1',
            'leader_name' => 'Coordinateur Amical',
            'schedule' => 'Selon calendrier',
            'gender_scope' => 'Adultes',
            'sort_order' => 6,
        ],
    ],
    'publications' => [
        [
            'title' => 'Statuts du Groupe Scout Saint Nicolas',
            'type' => 'statut',
            'unit_slug' => null,
            'author' => 'Chef de groupe',
            'excerpt' => 'Document de reference sur le fonctionnement du groupe et ses responsabilites.',
            'body' => 'Statuts officiels regissant l’organisation, la vision et le fonctionnement du Groupe Scout Saint Nicolas.',
            'publication_date' => '2026-01-15',
            'sort_order' => 1,
        ],
        [
            'title' => 'Reglement interieur 2026',
            'type' => 'reglement',
            'unit_slug' => null,
            'author' => 'Conseil de groupe',
            'excerpt' => 'Regles de vie, discipline et securite applicables a toutes les unites.',
            'body' => 'Regles de vie et de conduite applicables a l’ensemble des membres et responsables.',
            'publication_date' => '2026-01-20',
            'sort_order' => 2,
        ],
        [
            'title' => 'Code de conduite de la Meute',
            'type' => 'reglement',
            'unit_slug' => 'meute',
            'author' => 'Akela',
            'excerpt' => 'Repere educatif adapte aux plus jeunes membres du groupe.',
            'body' => 'Code de conduite specifique aux louvetaux et a leurs responsables.',
            'publication_date' => '2026-02-04',
            'sort_order' => 3,
        ],
        [
            'title' => "Retour d'experience du camp de la Troupe M",
            'type' => 'article',
            'unit_slug' => 'troupe-m',
            'author' => 'Equipe Troupe M',
            'excerpt' => "Compte-rendu des activites, de la progression et des apprentissages du dernier camp.",
            'body' => "Retour d'experience sur les temps forts du camp et les lecons retenues par l'unite.",
            'publication_date' => '2026-02-18',
            'sort_order' => 4,
        ],
        [
            'title' => 'Calendrier des activites 2026',
            'type' => 'annonce',
            'unit_slug' => null,
            'author' => 'Secretariat',
            'excerpt' => "Vue d'ensemble des grands rendez-vous de l'annee scoute.",
            'body' => 'Planning general des activites annuelles du groupe pour faciliter la coordination.',
            'publication_date' => '2026-03-01',
            'sort_order' => 5,
        ],
    ],
    'gallery' => [
        [
            'title' => 'Identite du groupe',
            'unit_slug' => null,
            'event_name' => 'Vie du groupe',
            'media_type' => 'image',
            'media_path' => 'images/logo-gsn.png',
            'caption' => 'Le signe de ralliement du Groupe Scout Saint Nicolas.',
            'taken_at' => '2026-01-10',
            'sort_order' => 1,
        ],
        [
            'title' => 'Temps fort Meute',
            'unit_slug' => 'meute',
            'event_name' => 'Jeu de piste',
            'media_type' => 'image',
            'media_path' => 'images/logo-gsn.png',
            'caption' => 'Illustration de la vie de la Meute.',
            'taken_at' => '2026-02-08',
            'sort_order' => 2,
        ],
        [
            'title' => 'Service de la Grappe',
            'unit_slug' => 'grappe',
            'event_name' => 'Action communautaire',
            'media_type' => 'image',
            'media_path' => 'images/logo-gsn.png',
            'caption' => 'Projet de service porte par la Grappe.',
            'taken_at' => '2026-03-05',
            'sort_order' => 3,
        ],
    ],
    'members' => [
        [
            'unit_slug' => 'meute',
            'first_name' => 'Nathan',
            'last_name' => 'Ndayisaba',
            'email' => 'nathan@example.com',
            'phone' => '',
            'birth_date' => '2017-05-10',
            'gender' => 'Masculin',
            'address' => 'Bujumbura',
            'parent_name' => 'Jean Ndayisaba',
            'medical_notes' => 'Aucune',
            'motivation' => "Decouvrir le scoutisme et apprendre a vivre en equipe.",
            'status' => 'active',
            'member_function' => 'Membre',
            'role_title' => null,
            'registered_at' => '2026-01-14',
        ],
        [
            'unit_slug' => 'troupe-f',
            'first_name' => 'Deborah',
            'last_name' => 'Nkurunziza',
            'email' => 'deborah@example.com',
            'phone' => '',
            'birth_date' => '2012-09-22',
            'gender' => 'Feminin',
            'address' => 'Bujumbura',
            'parent_name' => 'Claire Nkurunziza',
            'medical_notes' => 'Aucune',
            'motivation' => 'Vivre les camps et progresser dans la methode scoute.',
            'status' => 'active',
            'member_function' => 'Membre',
            'role_title' => null,
            'registered_at' => '2026-01-17',
        ],
        [
            'unit_slug' => 'troupe-m',
            'first_name' => 'Lionel',
            'last_name' => 'Havyarimana',
            'email' => 'lionel@example.com',
            'phone' => '',
            'birth_date' => '2011-07-14',
            'gender' => 'Masculin',
            'address' => 'Bujumbura',
            'parent_name' => 'Didier Havyarimana',
            'medical_notes' => 'Aucune',
            'motivation' => "Apprendre l'orientation et les techniques de camp.",
            'status' => 'pending',
            'member_function' => 'Membre',
            'role_title' => null,
            'registered_at' => '2026-03-18',
        ],
        [
            'unit_slug' => 'grappe',
            'first_name' => 'Aline',
            'last_name' => 'Bizimana',
            'email' => 'aline@example.com',
            'phone' => '',
            'birth_date' => '2008-03-09',
            'gender' => 'Feminin',
            'address' => 'Bujumbura',
            'parent_name' => 'Marie Bizimana',
            'medical_notes' => 'Aucune',
            'motivation' => 'Servir la communaute et preparer des projets utiles.',
            'status' => 'active',
            'member_function' => 'Membre',
            'role_title' => null,
            'registered_at' => '2026-02-02',
        ],
        [
            'unit_slug' => 'route',
            'first_name' => 'Cedric',
            'last_name' => 'Nduwimana',
            'email' => 'cedric@example.com',
            'phone' => '+25779000001',
            'birth_date' => '2004-12-01',
            'gender' => 'Masculin',
            'address' => 'Bujumbura',
            'parent_name' => null,
            'medical_notes' => 'Aucune',
            'motivation' => 'Mieux servir et accompagner les plus jeunes.',
            'status' => 'active',
            'member_function' => 'Membre',
            'role_title' => null,
            'registered_at' => '2026-01-29',
        ],
        [
            'unit_slug' => 'amical',
            'first_name' => 'Sandrine',
            'last_name' => 'Niyonkuru',
            'email' => 'sandrine@example.com',
            'phone' => '+25779000002',
            'birth_date' => '1995-11-25',
            'gender' => 'Feminin',
            'address' => 'Bujumbura',
            'parent_name' => null,
            'medical_notes' => 'Aucune',
            'motivation' => 'Mettre mon experience au service de la formation des jeunes.',
            'status' => 'active',
            'member_function' => 'Maitrise',
            'role_title' => 'Coordinatrice',
            'registered_at' => '2026-02-24',
        ],
    ],
    'program_events' => [
        [
            'unit_slug' => null,
            'title' => 'Rassemblement general du groupe',
            'description' => 'Rencontre commune de toutes les unites pour la coordination, la fraternite et les annonces du groupe.',
            'event_date' => '2026-04-05',
            'time_label' => '09:00 - 12:30',
            'responsible' => 'Chef de groupe',
            'location' => 'Cour du groupe',
            'sort_order' => 0,
        ],
        [
            'unit_slug' => null,
            'title' => 'Journee de service communautaire',
            'description' => 'Action du groupe mobilisant toutes les unites autour d un service concret a rendre a la communaute.',
            'event_date' => '2026-04-19',
            'time_label' => '08:00 - 13:00',
            'responsible' => 'Conseil de groupe',
            'location' => 'Quartier Saint Nicolas',
            'sort_order' => 0,
        ],
        [
            'unit_slug' => 'meute',
            'title' => 'Grand jeu en foret',
            'description' => "Apprendre a cooperer, observer et respecter la nature.",
            'event_date' => '2026-04-06',
            'time_label' => '08:30 - 11:30',
            'responsible' => 'Akela',
            'location' => 'Parc de la ville',
            'sort_order' => 1,
        ],
        [
            'unit_slug' => 'troupe-f',
            'title' => "Atelier d'orientation",
            'description' => 'Lecture de carte, boussole et travail en patrouille.',
            'event_date' => '2026-04-13',
            'time_label' => '14:00 - 17:00',
            'responsible' => 'Cheftaine Troupe F',
            'location' => 'Cour du groupe',
            'sort_order' => 1,
        ],
        [
            'unit_slug' => 'troupe-m',
            'title' => 'Preparation du camp',
            'description' => 'Construction legere, materiel et organisation des equipes.',
            'event_date' => '2026-04-20',
            'time_label' => '14:00 - 17:00',
            'responsible' => 'Chef Troupe M',
            'location' => 'Terrain scout',
            'sort_order' => 1,
        ],
        [
            'unit_slug' => 'grappe',
            'title' => 'Projet de service local',
            'description' => "Action communautaire avec planification, execution et evaluation d'impact.",
            'event_date' => '2026-04-27',
            'time_label' => '09:00 - 12:00',
            'responsible' => 'President Grappe',
            'location' => 'Quartier Saint Nicolas',
            'sort_order' => 1,
        ],
        [
            'unit_slug' => 'route',
            'title' => 'Marche et partage',
            'description' => 'Temps de route, reflexion et service concret.',
            'event_date' => '2026-05-04',
            'time_label' => '07:30 - 13:00',
            'responsible' => 'Chef Route',
            'location' => 'Bujumbura rural',
            'sort_order' => 1,
        ],
        [
            'unit_slug' => 'amical',
            'title' => "Reunion d'appui aux unites",
            'description' => "Coordination du soutien logistique, financier et pedagogique du groupe.",
            'event_date' => '2026-05-10',
            'time_label' => '16:00 - 18:00',
            'responsible' => 'Coordinateur Amical',
            'location' => 'Salle de reunion',
            'sort_order' => 1,
        ],
    ],
];
